### ISSUE TITLE
Function that returns size_t is meant to return -1

### ISSUE THREAD

**Issue by thomas-vaiarella** [canonsawrey/CS4500-API#10]
Since this function returns a size_t, the return value must be >= 0. When returning -1, we actually get the max size_t value. Either the return type should be changed, or the spec should mention returning a non-negative value in the case of not finding an element.

https://github.com/canonsawrey/CS4500-API/blob/57ed52ea8a2aa04d628b4dbbd3ae5c67f79924af/array.h#L82

**Comment by chitalian** [comment]
good point^

**Comment by canonsawrey** [comment]
Changing to int

**Comment by canonsawrey** [comment]
Fixed in https://github.com/canonsawrey/CS4500-API/pull/13
