### ISSUE TITLE
hash_me() setting undeclared variable

### ISSUE THREAD

**Issue by thomas-vaiarella** [canonsawrey/CS4500-API#8]
It appears that hash_ is never declared in the TestObject class

https://github.com/canonsawrey/CS4500-API/blob/57ed52ea8a2aa04d628b4dbbd3ae5c67f79924af/test-array.cpp#L21

**Comment by chitalian** [comment]
I think it overrides the hash_me in the Object

**Comment by canonsawrey** [comment]
It originally did that, but we changed our object to the shared class library, and that broke a few things in test-array.cpp. Fixing

**Comment by canonsawrey** [comment]
Fixed in https://github.com/canonsawrey/CS4500-API/pull/13
