### ISSUE TITLE
Mistake in test

### ISSUE THREAD

**Issue by thomas-vaiarella** [canonsawrey/CS4500-API#9]
In this test, either it should be t_false or get(1)

https://github.com/canonsawrey/CS4500-API/blob/57ed52ea8a2aa04d628b4dbbd3ae5c67f79924af/test-array.cpp#L227

**Comment by chitalian** [comment]
https://github.com/canonsawrey/CS4500-API/pull/12

**Comment by canonsawrey** [comment]
Fixed in https://github.com/canonsawrey/CS4500-API/pull/13
